export default {
    addressInformation: {
        shipping_address: {
            customerAddressId: '0',
            countryId: 'IT',
            regionId: '0',
            regionCode: 'mi',
            region: 'mi',
            street: ['bastioni di porta nuova 12'],
            postcode: '20121',
            city: 'milano',
            customerId: '0',
            telephone: '',
            firstname: '',
            lastname: '',
        },
        billing_address: {
            customerAddressId: '0',
            countryId: 'IT',
            regionId: '0',
            regionCode: 'mi',
            region: 'mi',
            street: ['bastioni di porta nuova 12'],
            postcode: '20121',
            city: 'milano',
            customerId: '0',
            telephone: '',
            firstname: '',
            lastname: '',
            saveInAddressBook: null,
        },
        shipping_method_code: 'flatrate',
        shipping_carrier_code: 'flatrate',
    },
}
